-- Superado: no ejecutar este archivo (el DELETE viejo borraba también Imputados).
-- Fuente actual: sql/supabase_cb_retirar_solo_no_imputado.sql
-- Galicia: un movimiento Imputado no se retira; solo En proceso (u otro no imputado)
-- ausente en este Excel. Tesorería no se toca. No aplica a PDF.
